### ISSUE TITLE
Startup example

### ISSUE THREAD

**Issue by Outstep** [Ahrotahntee/automatic-tinc#1]
Hello,

I have 4 CoreOS nodes on VPS servers each with public IP's and would like to try and see if it would be possible to use your automatic-tinc to establish secure VPN's between these nodes located across the internet.

Could you please give me an example of how I might be able to start Tinc on the CoreOS cluster nodes

Thanks,
Lonnie

**Comment by Ahrotahntee** [comment]
I apologize for not responding earlier. I have not been an active developer lately.

Automatic-tinc is designed to be used on CoreOS nodes that share an etcd2 instance, so if all the nodes are connected via etcd2 - there is no problem. Simply use the example unit file in the README.
